trigger:
- staging

pr:
- staging

stages:
  - stage:
    displayName: Analyze
    jobs:
      - job: analyze
        pool:
          vmImage: windows-latest
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore Solution
            inputs:
              command: restore
              projects: '*/*.csproj'
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'sonarcloud connection'
              organization: 121420-dotnet-sonarcloud
              projectKey: OutOfTheParkStatService
              projectName: OutOfTheParkStatService
              scannerMode: MSBuild
              extraProperties: |
                sonar.exclusions=**/obj/**,**/lib/**,**/*.dll,**/Migrations/**
          - script: dotnet build --configuration Release
            displayName: Analyze Build
          - task: DotNetCoreCLI@2
            inputs:
              command: test
              projects: '*.Tests/*.csproj'
              arguments: --configuration Release --collect "Code Coverage"
          - task: PublishCodeCoverageResults@1
            displayName: Publish Code Coverage Results
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: $(Agent.TempDirectory)/*/cobertura/coverage.xml
          - task: SonarCloudAnalyze@1
            displayName: Run Code Analysis
          - task: SonarCloudPublish@1
            displayName: Publish Code Analysis
  - stage:
    displayName: Register
    jobs:
      - job: register
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            inputs:
              command: login
              containerRegistry: 'Container Registry Connection'
          - script: |
              docker image build -t outofthepark15226.azurecr.io/stat-service:latest .
              docker image push outofthepark15226.azurecr.io/stat-service:latest
          - task: Docker@2
            inputs:
              command: logout
              containerRegistry: 'Container Registry Connection'
